# Site settings
title: GetItFixed!
email: info@camptocamp.com
description: GetItFixed! is a Web application to localise problem in the environment. # this means to ignore newlines until "baseurl:"
baseurl: "/gif_website/" # the subpath of your site, e.g. /blog/
url: "https://camptocamp.github.io/gif_website/" # the base hostname & protocol for your site

twitter_username: camptocamp_geo
github_username: camptocamp

# Build settings
markdown: kramdown

exclude: ["README.md", vendor]
